### ISSUE TITLE
サバイバルのページ作成

### ISSUE THREAD

**Issue by graycat27** [JavaJava19/jps.gg#61]

**Comment by ThreeStraw** [comment]
[Survival(看板の説明無).txt](https://github.com/JavaJava19/jps.gg/files/12123508/Survival.txt)

**Comment by graycat27** [comment]
@ThreeStraw https://github.com/JavaJava19/jps.gg/blob/work-61survive/source/src/components/parts/game/Survival.js
実装に際して文面の調整をしています。上記ソースの日本語を追っていただいて、文意相違ないか確認をお願いします

**Comment by ThreeStraw** [comment]
![image](https://github.com/JavaJava19/jps.gg/assets/136431350/4e3f2956-8fa8-4a04-a5b1-8a4bfc289dcf)
![image](https://github.com/JavaJava19/jps.gg/assets/136431350/d315448a-e5b0-4d00-be3a-717b40d34e75)
![image](https://github.com/JavaJava19/jps.gg/assets/136431350/e4d66718-51fa-432b-97aa-af03f35217ac)
![image](https://github.com/JavaJava19/jps.gg/assets/136431350/48de0b88-f883-4402-8a87-1f359e0d1a35)
![image](https://github.com/JavaJava19/jps.gg/assets/136431350/fce21348-d26d-41fe-b629-629337bf5704)
![door](https://github.com/JavaJava19/jps.gg/assets/136431350/a183bd75-40b7-4d3d-9121-3fcae140c359)

**Comment by ThreeStraw** [comment]
[BlockLocker.txt](https://github.com/JavaJava19/jps.gg/files/12169510/BlockLocker.txt)

**Comment by graycat27** [comment]
@ThreeStraw 
![image](https://github.com/JavaJava19/jps.gg/assets/64903817/9c8e4f26-c711-49d0-bdad-2da59f3e22e5)
ドアは隣接ブロックへの貼り付けでも保護が効くという仕様になっているのですが、言及してもらってもいいですか？

いい感じにやると、壁の下に保護設定を隠すことができて、見た目すっきりさせられたりも…。
![image](https://github.com/JavaJava19/jps.gg/assets/64903817/fa8801a3-6a19-4231-8983-97d311a257d3)

**Comment by ThreeStraw** [comment]
写真と文章書いてくるって事で合ってますか...?
合ってるなら確認取れ次第やります

**Comment by yui-Kitamura** [comment]
@ThreeStraw 上記情報を取り込んで、先日の `BlockLocker.txt` を更新していただけますでしょうか
