### ISSUE TITLE
規約（/read）の期日

### ISSUE THREAD

**Issue by graycat27** [JavaJava19/jps.gg#77]
初版適用開始日、更新版の日付 が書かれていない

**Comment by graycat27** [comment]
@az-aka 規約適用日、9/1に遡及はやや問題ありなので、近日を指定して更新かけたいんだけども、いつがいいかな  
JPS-Discordの [JPSの教科書]>[1.禁止事項について][2.宣伝及び売名]を包括して、教科書チャンネル自体に「規約全文はウェブサイトを参照ください」って追加すればいいと思ってる
それと、追記した旨軽くお知らせかな

**Comment by az-aka** [comment]
10/1いけますか？
完了次第お知らせ打ちます！
